### ISSUE TITLE
为什么老师的docker push 的速度会这么快

### ISSUE THREAD

**Issue by zhanyeye** [bwhyman/githubactions-examples#1]
https://github.com/bwhyman/githubactions-examples/blob/1ba377ad5b753563215cba15cad50a4f6053f5cf/.github/workflows/maven.yml#L26

为什么老师的docker push 只要50s 啊，我用的阿里docker仓库得要4~5分钟。

**Comment by bwhyman** [comment]
哇，这的仓库你都看见了
可能我的示例是仅包含了springmvc的springboot，层少，镜像比较小吧
测了一下，多容器涉及的容器变量/参数/敏感数据较多，在服务器创建一个docker-compose，用actions调用不错

**Comment by zhanyeye** [comment]
好的😁，我去学 docker-compose 看看
